# Generated by Django 4.2.4 on 2023-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectWiseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('company_id', models.CharField(max_length=100)),
                ('api_public_key', models.CharField(max_length=100)),
                ('api_private_key', models.CharField(max_length=100)),
            ],
        ),
    ]
