# Generated by Django 4.2.4 on 2023-11-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('vendor_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectWiseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('company_id', models.CharField(max_length=255)),
                ('api_public_key', models.CharField(max_length=255)),
                ('api_private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_company_statuses', models.ManyToManyField(blank=True, to='harmony.companystatus')),
                ('sync_company_types', models.ManyToManyField(blank=True, to='harmony.companytype')),
            ],
        ),
        migrations.CreateModel(
            name='DataverseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_url', models.URLField()),
                ('tenant_id', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig')),
                ('dataverse_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataverseconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.companymapping')),
            ],
        ),
        migrations.AddField(
            model_name='companytype',
            name='connectwise_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig'),
        ),
        migrations.AddField(
            model_name='companystatus',
            name='connectwise_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig'),
        ),
        migrations.AddField(
            model_name='companymapping',
            name='connectwise_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig'),
        ),
    ]
