# Generated by Django 4.2.4 on 2023-11-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectwiseconfig',
            name='api_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectwiseconfig',
            name='api_public_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connectwiseconfig',
            name='company_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('vendor_flag', models.BooleanField(default=False)),
                ('connectwise_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('inactive_flag', models.BooleanField(default=False)),
                ('connectwise_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig')),
            ],
        ),
    ]
