# Generated by Django 4.2.4 on 2023-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_alter_companymapping_connectwise_manage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymapping',
            name='connectwise_manage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
