# Generated by Django 4.2.4 on 2023-11-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_alter_connectwiseconfig_api_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatus',
            name='sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companytype',
            name='sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectwiseconfig',
            name='sync_company_statuses',
            field=models.ManyToManyField(blank=True, to='harmony.companystatus'),
        ),
        migrations.AddField(
            model_name='connectwiseconfig',
            name='sync_company_types',
            field=models.ManyToManyField(blank=True, to='harmony.companytype'),
        ),
    ]
