# Generated by Django 4.2.4 on 2023-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0003_companystatus_sync_enabled_companytype_sync_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystatus',
            name='inactive_flag',
        ),
    ]
