# Generated by Django 4.2.4 on 2023-11-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0003_alter_companymapping_connectwise_manage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemapping',
            name='dynamics365_company_id',
        ),
        migrations.RemoveField(
            model_name='sitemapping',
            name='dynamics365_name',
        ),
        migrations.CreateModel(
            name='ConnectWiseCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField(blank=True, null=True)),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig')),
            ],
        ),
        migrations.AlterField(
            model_name='sitemapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisecompany'),
        ),
        migrations.DeleteModel(
            name='CompanyMapping',
        ),
    ]
