# Generated by Django 4.2.4 on 2023-11-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0004_remove_sitemapping_dynamics365_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataverse_id', models.IntegerField(blank=True, null=True)),
                ('dataverse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataverse_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataverseconfig')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisecompany')),
                ('dataverse_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataverseaccount')),
                ('sync_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.syncmapping')),
            ],
        ),
    ]
