# Generated by Django 4.2.4 on 2023-11-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0004_remove_companystatus_inactive_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystatus',
            name='sync_enabled',
        ),
        migrations.RemoveField(
            model_name='companytype',
            name='sync_enabled',
        ),
    ]
