# Generated by Django 4.2.4 on 2023-11-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0005_dataverseaccount_companymapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectwiseconfig',
            unique_together={('base_url', 'company_id')},
        ),
    ]
