# Generated by Django 4.2.4 on 2023-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0005_remove_companystatus_sync_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwiseconfig')),
            ],
        ),
    ]
