# Generated by Django 4.2.4 on 2023-11-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0006_alter_connectwiseconfig_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverseaccount',
            name='dataverse_id',
        ),
    ]
