# Generated by Django 4.2.4 on 2023-11-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0006_companymapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymapping',
            old_name='connectwise_company_id',
            new_name='connectwise_manage_id',
        ),
    ]
