# Generated by Django 4.2.4 on 2023-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0007_remove_dataverseaccount_dataverse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataverseaccount',
            name='dataverse_id',
            field=models.UUIDField(default='3e59d1fe-5e07-4d5c-b94a-39a7d0959c39'),
            preserve_default=False,
        ),
    ]
