# Generated by Django 4.2.4 on 2023-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0007_rename_connectwise_company_id_companymapping_connectwise_manage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymapping',
            name='connectwise_manage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companymapping',
            name='dynamics365_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
