# Generated by Django 4.2.4 on 2023-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0008_dataverseaccount_dataverse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmapping',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
