# Generated by Django 4.2.4 on 2023-11-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0008_companymapping_connectwise_manage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamics365_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.companymapping')),
            ],
        ),
    ]
