# Generated by Django 4.2.4 on 2023-11-27 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion

def create_log_types(apps, schema_editor):
    LogType = apps.get_model('harmony', 'LogType')
    LogType.objects.create(name='Debug', id=0)
    LogType.objects.create(name='Info', id=1)
    LogType.objects.create(name='Warning', id=2)
    LogType.objects.create(name='Error', id=3)

class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0009_syncmapping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('area', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.logtype')),
            ],
        ),
         migrations.RunPython(create_log_types),
    ]
