# Generated by Django 4.2.4 on 2023-11-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0013_alter_log_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteMapping',
            new_name='ConnectWiseSite',
        ),
    ]
