# Generated by Django 4.2.4 on 2023-11-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0014_rename_sitemapping_connectwisesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectWiseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisesite')),
            ],
        ),
        migrations.CreateModel(
            name='DataverseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataverse_id', models.UUIDField()),
                ('dataverse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataverse_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataverseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisecontact')),
                ('dataverse_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataversecontact')),
                ('sync_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.syncmapping')),
            ],
        ),
    ]
