# Generated by Django 4.2.4 on 2023-11-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0016_delete_contactmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectWiseContact',
        ),
    ]
