# Generated by Django 4.2.4 on 2023-11-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0018_connectwisecontact_contactmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectwisecontact',
            old_name='site',
            new_name='connectwise_company',
        ),
    ]
