# Generated by Django 4.2.4 on 2023-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0019_rename_site_connectwisecontact_connectwise_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectwisecontact',
            name='connectwise_manage_name',
        ),
        migrations.AddField(
            model_name='connectwisecontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectwisecontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectwisecompany',
            name='connectwise_manage_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='connectwisecontact',
            name='connectwise_manage_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='connectwisesite',
            name='connectwise_manage_id',
            field=models.IntegerField(),
        ),
    ]
