# Generated by Django 4.2.4 on 2023-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0020_remove_connectwisecontact_connectwise_manage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataversecontact',
            name='dataverse_name',
        ),
        migrations.AddField(
            model_name='dataversecontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataversecontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
