# Generated by Django 4.2.4 on 2023-11-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0022_connectwisecompany_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataverseaccount',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harmony.dataversecontact'),
        ),
    ]
