# Generated by Django 4.2.4 on 2023-11-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0023_dataverseaccount_primary_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectWiseSite',
        ),
    ]
