# Generated by Django 4.2.4 on 2023-11-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0024_delete_connectwisesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectWiseSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_manage_id', models.IntegerField()),
                ('connectwise_manage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisecompany')),
            ],
        ),
    ]
