# Generated by Django 4.2.4 on 2023-12-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0025_connectwisesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataverseCustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataverse_id', models.UUIDField()),
                ('dataverse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataverse_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataverseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectwise_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.connectwisesite')),
                ('dataverse_customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.dataversecustomeraddress')),
                ('sync_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harmony.syncmapping')),
            ],
        ),
    ]
